### ISSUE TITLE
ow to Resolve Error When Running object_cluster.py

### ISSUE THREAD

**Issue by choibigo** [MIT-SPARK/Clio#7]
Hi everyone,

I’m currently working with the CLIo project and trying to execute the following command:
```python clio_batch/object_cluster.py /root/workspace/clio_datasets/office_graph/trial_0/large_fine/dsg.json /root/workspace/clio_datasets/office/tasks_office.yaml /root/workspace/clio_output /root/catkin_ws/src/clio/clio_eval/experiments/configs/cluster/large_delta_00001.yaml
```

However, i encountered the follow error message
```
(clio) root@cbigo-pc:~/catkin_ws/src/clio# python clio_batch/object_cluster.py /root/workspace/clio_datasets/cubicle_graph/trial_0/large_fine/dsg.json /root/workspace/clio_datasets/cubicle/tasks_cubicle.yaml /root/workspace/clio_output /root/catkin_ws/src/clio/clio_eval/experiments/configs/cluster/large_delta_00001.yaml
loading graph from '/root/workspace/clio_datasets/cubicle_graph/trial_0/large_fine/dsg.json'...
/root/workspace/clio_datasets/cubicle_graph/trial_0/large_fine/dsg.json ########################
[SPARK-DSG] [WARNING] Loading file with outdated encoding (main v1.0.0). This format may be discontinued in the future. For optimal preservation and performance load the file and save it again to update to the current encoding (main v1.0.4).
Traceback (most recent call last):
  File "clio_batch/object_cluster.py", line 207, in <module>
    main()
  File "/root/environments/clio/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/environments/clio/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/environments/clio/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/environments/clio/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "clio_batch/object_cluster.py", line 185, in main
    clustered_G = cluster_3d(str(scene_graph_path), task_file, output_folder,
  File "clio_batch/object_cluster.py", line 121, in cluster_3d
    G = dsg.DynamicSceneGraph.load(str(scene_graph_path))
RuntimeError: invalid attributes for l(0)
```

I’d appreciate it if someone could provide tips or guidance to troubleshoot this issue.

**Comment by Laura-Ting** [comment]
Hi,
I found that a `dsg.json` file can be generated each time in the `hydra/output/realsense/backend` dir after running `clio online`.

**Comment by chadrs2** [comment]
Do you get a dsg.json, by just running `roslaunch clio_ros realsense.launch <and other yaml arguments>`?
